//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS0108, CS0114
namespace Dan.Core.Helpers.Notification
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    public partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [DataMember()]
        public string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [DataMember()]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [DataMember()]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [DataMember()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="StandaloneNotificationBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10", ItemName="StandaloneNotification")]
    public class StandaloneNotificationBEList : System.Collections.Generic.List<StandaloneNotification>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="StandaloneNotification", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class StandaloneNotification : object
    {
        
        private string FromAddressField;
        
        private System.Nullable<bool> IsReservableField;
        
        private int LanguageIDField;
        
        private string NotificationTypeField;
        
        private ReceiverEndPointBEList ReceiverEndPointsField;
        
        private string ReporteeNumberField;
        
        private Roles RolesField;
        
        private Service ServiceField;
        
        private System.DateTime ShipmentDateTimeField;
        
        private TextTokenSubstitutionBEList TextTokensField;
        
        private System.Nullable<bool> UseServiceOwnerShortNameAsSenderOfSmsField;
        
        [DataMember()]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }
        
        [DataMember()]
        public System.Nullable<bool> IsReservable
        {
            get
            {
                return this.IsReservableField;
            }
            set
            {
                this.IsReservableField = value;
            }
        }
        
        [DataMember()]
        public int LanguageID
        {
            get
            {
                return this.LanguageIDField;
            }
            set
            {
                this.LanguageIDField = value;
            }
        }
        
        [DataMember()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [DataMember()]
        public ReceiverEndPointBEList ReceiverEndPoints
        {
            get
            {
                return this.ReceiverEndPointsField;
            }
            set
            {
                this.ReceiverEndPointsField = value;
            }
        }
        
        [DataMember()]
        public string ReporteeNumber
        {
            get
            {
                return this.ReporteeNumberField;
            }
            set
            {
                this.ReporteeNumberField = value;
            }
        }
        
        [DataMember()]
        public Roles Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [DataMember()]
        public Service Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime ShipmentDateTime
        {
            get
            {
                return this.ShipmentDateTimeField;
            }
            set
            {
                this.ShipmentDateTimeField = value;
            }
        }
        
        [DataMember()]
        public TextTokenSubstitutionBEList TextTokens
        {
            get
            {
                return this.TextTokensField;
            }
            set
            {
                this.TextTokensField = value;
            }
        }
        
        [DataMember()]
        public System.Nullable<bool> UseServiceOwnerShortNameAsSenderOfSms
        {
            get
            {
                return this.UseServiceOwnerShortNameAsSenderOfSmsField;
            }
            set
            {
                this.UseServiceOwnerShortNameAsSenderOfSmsField = value;
            }
        }

       /* public static implicit operator StandaloneNotification(StandaloneNotification v)
        {
            throw new NotImplementedException();
        }*/
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="Service", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06")]
    public partial class Service : object
    {
        
        private string ServiceCodeField;
        
        private int ServiceEditionField;
        
        [DataMember(IsRequired=true)]
        public string ServiceCode
        {
            get
            {
                return this.ServiceCodeField;
            }
            set
            {
                this.ServiceCodeField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public int ServiceEdition
        {
            get
            {
                return this.ServiceEditionField;
            }
            set
            {
                this.ServiceEditionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="ReceiverEndPointBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="ReceiverEndPoint")]
    public class ReceiverEndPointBEList : System.Collections.Generic.List<ReceiverEndPoint>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="Roles", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06", ItemName="RoleName")]
    public class Roles : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="TextTokenSubstitutionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="TextToken")]
    public class TextTokenSubstitutionBEList : System.Collections.Generic.List<TextToken>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="ReceiverEndPoint", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class ReceiverEndPoint : object
    {
        
        private System.Nullable<TransportType> TransportTypeField;
        
        private string ReceiverAddressField;
        
        [DataMember()]
        public System.Nullable<TransportType> TransportType
        {
            get
            {
                return this.TransportTypeField;
            }
            set
            {
                this.TransportTypeField = value;
            }
        }
        
        [DataMember(Order=1)]
        public string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="TransportType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    public enum TransportType : int
    {
        
        [EnumMember()]
        SMS = 1,
        
        [EnumMember()]
        Email = 2,
        
        [EnumMember()]
        IM = 3,
        
        [EnumMember()]
        Both = 4,
        
        [EnumMember()]
        SMSPreferred = 5,
        
        [EnumMember()]
        EmailPreferred = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="TextToken", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class TextToken : object
    {
        
        private int TokenNumField;
        
        private string TokenValueField;
        
        [DataMember()]
        public int TokenNum
        {
            get
            {
                return this.TokenNumField;
            }
            set
            {
                this.TokenNumField = value;
            }
        }
        
        [DataMember()]
        public string TokenValue
        {
            get
            {
                return this.TokenValueField;
            }
            set
            {
                this.TokenValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="SendNotificationResultList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06", ItemName="NotificationResult")]
    public class SendNotificationResultList : System.Collections.Generic.List<NotificationResult>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="NotificationResult", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06")]
    public partial class NotificationResult : object
    {
        
        private EndPointResultList EndPointsField;
        
        private string NotificationTypeField;
        
        private string ReporteeNumberField;
        
        [DataMember()]
        public EndPointResultList EndPoints
        {
            get
            {
                return this.EndPointsField;
            }
            set
            {
                this.EndPointsField = value;
            }
        }
        
        [DataMember()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [DataMember()]
        public string ReporteeNumber
        {
            get
            {
                return this.ReporteeNumberField;
            }
            set
            {
                this.ReporteeNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [CollectionDataContract(Name="EndPointResultList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06", ItemName="EndPointResult")]
    public class EndPointResultList : System.Collections.Generic.List<EndPointResult>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DataContract(Name="EndPointResult", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06")]
    public partial class EndPointResult : object
    {
        
        private string NameField;
        
        private string ReceiverAddressField;
        
        private System.Nullable<bool> RetrieveFromProfileField;
        
        private TransportType TransportTypeField;
        
        [DataMember()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [DataMember()]
        public string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
        
        [DataMember()]
        public System.Nullable<bool> RetrieveFromProfile
        {
            get
            {
                return this.RetrieveFromProfileField;
            }
            set
            {
                this.RetrieveFromProfileField = value;
            }
        }
        
        [DataMember()]
        public TransportType TransportType
        {
            get
            {
                return this.TransportTypeField;
            }
            set
            {
                this.TransportTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", ConfigurationName="Dan.Core.Helpers.Notification.INotificationAgencyExternalBasic")]
    public interface INotificationAgencyExternalBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<TestResponse> TestAsync(TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasic", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicResponse> SendStandaloneNotificationBasicAsync(SendStandaloneNotificationBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV2AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicV2Response> SendStandaloneNotificationBasicV2Async(SendStandaloneNotificationBasicV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalBasic/SendStandaloneNotificationBasicV3AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicV3Response> SendStandaloneNotificationBasicV3Async(SendStandaloneNotificationBasicV3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasic", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicRequestBody Body;
        
        public SendStandaloneNotificationBasicRequest()
        {
        }
        
        public SendStandaloneNotificationBasicRequest(SendStandaloneNotificationBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationBasicRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicRequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicRequestBody(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicResponse", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicResponseBody Body;
        
        public SendStandaloneNotificationBasicResponse()
        {
        }
        
        public SendStandaloneNotificationBasicResponse(SendStandaloneNotificationBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class SendStandaloneNotificationBasicResponseBody
    {
        
        public SendStandaloneNotificationBasicResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV2", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicV2RequestBody Body;
        
        public SendStandaloneNotificationBasicV2Request()
        {
        }
        
        public SendStandaloneNotificationBasicV2Request(SendStandaloneNotificationBasicV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationBasicV2RequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicV2RequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicV2RequestBody(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV2Response", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicV2ResponseBody Body;
        
        public SendStandaloneNotificationBasicV2Response()
        {
        }
        
        public SendStandaloneNotificationBasicV2Response(SendStandaloneNotificationBasicV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationBasicV2ResponseBody
    {
        
        [DataMember(Order=0)]
        public string SendStandaloneNotificationBasicV2Result;
        
        public SendStandaloneNotificationBasicV2ResponseBody()
        {
        }
        
        public SendStandaloneNotificationBasicV2ResponseBody(string SendStandaloneNotificationBasicV2Result)
        {
            this.SendStandaloneNotificationBasicV2Result = SendStandaloneNotificationBasicV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV3", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicV3RequestBody Body;
        
        public SendStandaloneNotificationBasicV3Request()
        {
        }
        
        public SendStandaloneNotificationBasicV3Request(SendStandaloneNotificationBasicV3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationBasicV3RequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationBasicV3RequestBody()
        {
        }
        
        public SendStandaloneNotificationBasicV3RequestBody(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationBasicV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationBasicV3Response", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public SendStandaloneNotificationBasicV3ResponseBody Body;
        
        public SendStandaloneNotificationBasicV3Response()
        {
        }
        
        public SendStandaloneNotificationBasicV3Response(SendStandaloneNotificationBasicV3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationBasicV3ResponseBody
    {
        
        [DataMember(Order=0)]
        public SendNotificationResultList SendStandaloneNotificationBasicV3Result;
        
        public SendStandaloneNotificationBasicV3ResponseBody()
        {
        }
        
        public SendStandaloneNotificationBasicV3ResponseBody(SendNotificationResultList SendStandaloneNotificationBasicV3Result)
        {
            this.SendStandaloneNotificationBasicV3Result = SendStandaloneNotificationBasicV3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface INotificationAgencyExternalBasicChannel : INotificationAgencyExternalBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NotificationAgencyExternalBasicClient : System.ServiceModel.ClientBase<INotificationAgencyExternalBasic>, INotificationAgencyExternalBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationAgencyExternalBasicClient() : 
                base(NotificationAgencyExternalBasicClient.GetDefaultBinding(), NotificationAgencyExternalBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), NotificationAgencyExternalBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationAgencyExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestResponse> INotificationAgencyExternalBasic.TestAsync(TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestResponse> TestAsync()
        {
            TestRequest inValue = new TestRequest();
            return ((INotificationAgencyExternalBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicResponse> INotificationAgencyExternalBasic.SendStandaloneNotificationBasicAsync(SendStandaloneNotificationBasicRequest request)
        {
            return base.Channel.SendStandaloneNotificationBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendStandaloneNotificationBasicResponse> SendStandaloneNotificationBasicAsync(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            SendStandaloneNotificationBasicRequest inValue = new SendStandaloneNotificationBasicRequest();
            inValue.Body = new SendStandaloneNotificationBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicV2Response> INotificationAgencyExternalBasic.SendStandaloneNotificationBasicV2Async(SendStandaloneNotificationBasicV2Request request)
        {
            return base.Channel.SendStandaloneNotificationBasicV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SendStandaloneNotificationBasicV2Response> SendStandaloneNotificationBasicV2Async(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            SendStandaloneNotificationBasicV2Request inValue = new SendStandaloneNotificationBasicV2Request();
            inValue.Body = new SendStandaloneNotificationBasicV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendStandaloneNotificationBasicV3Response> INotificationAgencyExternalBasic.SendStandaloneNotificationBasicV3Async(SendStandaloneNotificationBasicV3Request request)
        {
            return base.Channel.SendStandaloneNotificationBasicV3Async(request);
        }
        
        public System.Threading.Tasks.Task<SendStandaloneNotificationBasicV3Response> SendStandaloneNotificationBasicV3Async(string systemUserName, string systemPassword, StandaloneNotificationBEList standaloneNotifications)
        {
            SendStandaloneNotificationBasicV3Request inValue = new SendStandaloneNotificationBasicV3Request();
            inValue.Body = new SendStandaloneNotificationBasicV3RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((INotificationAgencyExternalBasic)(this)).SendStandaloneNotificationBasicV3Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic))
            {
                return new System.ServiceModel.EndpointAddress("https://www.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotificationAgencyExternalBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotificationAgencyExternalBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotificationAgencyExternalBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INotificationAgencyExternalBasic,
        }
    }
}
