name: Dan.Core CI/CD

permissions:
  actions: read

on:
 push:
   branches: [ master ]
   paths-ignore:
     - '**/README.md'
     - '**/*.yml'
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: '10.0.x'
      - name: 'Dotnet restore, build & test'
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
        working-directory: './'
      - name: Dotnet build and publish Function App with configuration 'Release'
        run: |
          dotnet build --configuration 'Release'
          dotnet publish -c 'Release' --no-restore -o './published-app'
        working-directory: 'Dan.Core'
      - name: Upload artifact 'dan-core'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: 'dan-core'
          path: Dan.Core/published-app
          include-hidden-files: true
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: [build]
    steps:
      - name: 'Download artifact for dev'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: 'dan-core'
          path: './downloaded-app'
      - name: 'Deploy artifact to dev'
        uses: azure/functions-action@02a16c5f3a5707fa97fca56c202cc2ef6cc7dccb # v1.5.4
        with:
          app-name: ${{secrets.FUNCTIONAPP_NAME}}
          package: './downloaded-app'
          publish-profile: ${{secrets.AZURE_FUNCTION_PUBLISH_CREDS}}

  post-deploy-dev:
    uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@077be64090710476cb8103764dd85154af8214eb
    needs: [deploy-dev]
    with:
      environment: 'dev'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      kvname: ${{ secrets.KVNAME }}    

  
  deploy-staging:   
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: [deploy-dev]
    steps:
      - name: 'Download artifact for staging'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: 'dan-core'
          path: './downloaded-app'
      - name: 'Deploy artifact to staging'
        uses: azure/functions-action@02a16c5f3a5707fa97fca56c202cc2ef6cc7dccb # v1.5.4
        with:
          app-name: ${{secrets.FUNCTIONAPP_NAME}}
          package: './downloaded-app'
          publish-profile: ${{secrets.AZURE_FUNCTION_PUBLISH_CREDS}}
  
  post-deploy-staging:
    uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@077be64090710476cb8103764dd85154af8214eb
    needs: [deploy-staging]
    with:
      environment: 'staging'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      kvname: ${{ secrets.KVNAME }}
 
      
  swap-staging-prod:   
    runs-on: ubuntu-latest
    environment: 'production'
    needs: [deploy-staging]
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Swap staging and production'
        run: |
          az webapp deployment slot swap -g '${{ secrets.RESOURCE_GROUP_PROD }}' -n '${{ secrets.FUNCTIONAPP_NAME }}' --slot 'staging' --target-slot 'production'
      - name: 'Azure logout'
        run: |
          az logout

  redeploy-staging:
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: [swap-staging-prod]
    steps:
      - name: 'Download artifact for redeploy to staging'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: 'dan-core'
          path: './downloaded-app'
      - name: 'Redeploy artifact to staging'
        uses: azure/functions-action@02a16c5f3a5707fa97fca56c202cc2ef6cc7dccb # v1.5.4
        with:
          app-name: ${{secrets.FUNCTIONAPP_NAME}}
          package: './downloaded-app'
          publish-profile: ${{secrets.AZURE_FUNCTION_PUBLISH_CREDS}}
        
