name: Post deploy test
permissions:
  actions: read
  contents: read
  id-token: write
  checks: write
  pull-requests: write
on:
 workflow_dispatch:
jobs:
 run:
   uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@28817d886fe657244d267c56480d9d0694b71f9b
   with:
     environment: 'dev'
   secrets:
     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
     kvname: ${{ secrets.KVNAME }}
