name: Post deploy test
on:
 workflow_dispatch:
jobs:
 run:
   uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@009dae7d9c3f0ddab3c1be13fe0c76177e174d74
   with:
     environment: 'dev'
   secrets:
     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
     kvname: ${{ secrets.KVNAME }}
