name: Post deploy test
permissions:
  actions: read
  contents: read
  id-token: write
  checks: write
  pull-requests: write
on:
 workflow_dispatch:
jobs:
 run:
   uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@077be64090710476cb8103764dd85154af8214eb
   with:
     environment: 'dev'
   secrets:
     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
     kvname: ${{ secrets.KVNAME }}
